LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := QuickAccessWalletMod
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := QuickAccessWallet.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := QuickAccessWallet
include $(BUILD_PREBUILT)
