LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := PixelThemesStubMod
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := PixelThemesStub.apk
LOCAL_MODULE_TAGS := optional
LOCAL_PRODUCT_MODULE := true
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := PixelThemesStub
LOCAL_DEX_PREOPT := false

include $(BUILD_PREBUILT)
